"""
file_parser.py
Handles Step 2-3 of the pipeline: detect file type, extract raw text,
clean it, and prepare it for chunking.

Supported formats: .pdf, .docx, .doc (best-effort), .txt, and standalone
pictures (PNG/JPG/JPEG/WEBP/GIF/BMP).

Kept in sync with the desktop LPTest's file_parser.py (same pipeline,
same ExtractionResult shape, same embedded-image support) with ONE
deliberate difference: .docx is parsed with the stdlib (zipfile +
xml.etree.ElementTree) instead of the `python-docx` package. `python-docx`
pulls in `lxml`, which is a known-fragile recipe under python-for-android
(see generate_questions_with_gemini()'s docstring in question_generator.py
for the same tradeoff on the AI-SDK side) -- the hand-rolled XML reader
avoids that risk entirely while still extracting both text and embedded
images.
"""

from __future__ import annotations
import os
import re
import base64
from dataclasses import dataclass, field
from typing import Optional

# Images (standalone uploads, or pulled out of a PDF/DOCX) are capped so a
# single file can't balloon into a huge, expensive AI request.
MAX_IMAGES_PER_FILE = 6
IMAGE_EXTS = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg",
              "webp": "image/webp", "gif": "image/gif", "bmp": "image/bmp"}


@dataclass
class ExtractionResult:
    text: str = ""
    headings: list[tuple[str, int]] = field(default_factory=list)  # (heading_text, char_offset)
    warning: Optional[str] = None      # non-fatal notice shown to the user
    error: Optional[str] = None        # fatal problem, extraction failed
    images: list[str] = field(default_factory=list)  # base64 data: URLs, for vision models


def detect_file_type(filepath: str) -> str:
    """Detect file type from extension (MIME sniffing kept simple/offline)."""
    ext = os.path.splitext(filepath)[1].lower().lstrip(".")
    if ext in ("pdf",):
        return "pdf"
    if ext in ("docx",):
        return "docx"
    if ext in ("doc",):
        return "doc"
    if ext in ("txt",):
        return "txt"
    if ext in IMAGE_EXTS:
        return "image"
    return "unknown"


def _to_data_url(raw_bytes: bytes, mime_type: str) -> str:
    encoded = base64.b64encode(raw_bytes).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def _extract_image(filepath: str) -> ExtractionResult:
    """A standalone picture upload -- no text to pull out; the picture
    itself gets sent straight to the vision model."""
    ext = os.path.splitext(filepath)[1].lower().lstrip(".")
    mime_type = IMAGE_EXTS.get(ext, "image/png")
    try:
        with open(filepath, "rb") as f:
            raw = f.read()
    except Exception as e:
        return ExtractionResult(error=f"Couldn't open this image ({e}).")
    if not raw:
        return ExtractionResult(error="This image file appears to be empty.")
    return ExtractionResult(
        text="",
        images=[_to_data_url(raw, mime_type)],
        warning="This is a picture file with no text of its own -- questions will be "
                "generated by having an AI model look at the picture directly.",
    )


def _extract_pdf(filepath: str) -> ExtractionResult:
    try:
        from pypdf import PdfReader
    except ImportError:
        return ExtractionResult(error="PDF support isn't installed. Run: pip install pypdf")

    result = ExtractionResult()
    try:
        reader = PdfReader(filepath)
    except Exception as e:
        return ExtractionResult(error=f"Couldn't open this PDF ({e}).")

    if getattr(reader, "is_encrypted", False):
        try:
            reader.decrypt("")
        except Exception:
            return ExtractionResult(error="This PDF is password-protected. Please remove the password and try again.")

    page_texts = []
    for page in reader.pages:
        try:
            page_texts.append(page.extract_text() or "")
        except Exception:
            page_texts.append("")

    total_chars = sum(len(t.strip()) for t in page_texts)
    avg_chars_per_page = total_chars / max(len(page_texts), 1)

    # Best-effort: pull out embedded pictures (diagrams, charts, photos
    # inside the PDF) even if the text extraction below fails/empties out --
    # a scanned PDF where every page IS a picture still has a shot at
    # generating questions via the images, so this runs before the
    # "no extractable text" early return.
    embedded_images: list[str] = []
    try:
        for page in reader.pages:
            for img in getattr(page, "images", []):
                if len(embedded_images) >= MAX_IMAGES_PER_FILE:
                    break
                ext = os.path.splitext(img.name)[1].lower().lstrip(".")
                mime_type = IMAGE_EXTS.get(ext)
                if not mime_type:
                    continue  # skip formats a vision model can't read (e.g. raw CCITT)
                embedded_images.append(_to_data_url(img.data, mime_type))
            if len(embedded_images) >= MAX_IMAGES_PER_FILE:
                break
    except Exception:
        pass  # image extraction is a bonus, never fatal to the text pipeline

    if total_chars == 0:
        if embedded_images:
            return ExtractionResult(
                images=embedded_images,
                warning="This looks like a scanned/image-based PDF with no extractable text -- "
                        "questions will be generated by having an AI model read the pages as pictures.",
            )
        return ExtractionResult(
            error="This looks like a scanned/image-based PDF with no extractable text. "
                  "Please run OCR on it (e.g. Adobe Acrobat, Google Drive OCR) and re-upload."
        )
    if avg_chars_per_page < 40 and len(page_texts) > 1:
        result.warning = (
            "This PDF has very little extractable text per page — it may be partially "
            "scanned. Some pages might be skipped. OCR is recommended for best results."
        )

    # Remove repeated header/footer lines (appear on most pages -> noise)
    line_counts: dict[str, int] = {}
    for t in page_texts:
        for line in set(l.strip() for l in t.splitlines() if l.strip()):
            line_counts[line] = line_counts.get(line, 0) + 1
    noisy_lines = {
        line for line, count in line_counts.items()
        if len(page_texts) > 2 and count >= max(3, int(len(page_texts) * 0.6)) and len(line) < 80
    }

    cleaned_pages = []
    for t in page_texts:
        kept = [l for l in t.splitlines() if l.strip() not in noisy_lines]
        cleaned_pages.append("\n".join(kept))

    result.text = "\n\n".join(cleaned_pages)
    result.images = embedded_images
    return result


# --- DOCX (stdlib-only: zipfile + ElementTree, no python-docx/lxml) -------
_W_NS = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
_HEADING_STYLE_RE = re.compile(r"heading\s*\d", re.IGNORECASE)


def _docx_heading_style_ids(zf) -> set[str]:
    """Reads word/styles.xml and returns the set of style IDs whose name
    (or ID) looks like 'HeadingN', so paragraphs using them can be flagged
    as headings without needing python-docx."""
    heading_ids: set[str] = set()
    try:
        import xml.etree.ElementTree as ET
        with zf.open("word/styles.xml") as f:
            tree = ET.parse(f)
    except Exception:
        return heading_ids
    for style in tree.getroot().findall(f"{_W_NS}style"):
        style_id = style.get(f"{_W_NS}styleId", "")
        name_el = style.find(f"{_W_NS}name")
        name_val = name_el.get(f"{_W_NS}val", "") if name_el is not None else ""
        if _HEADING_STYLE_RE.search(style_id) or _HEADING_STYLE_RE.search(name_val):
            heading_ids.add(style_id)
    return heading_ids


def _extract_docx(filepath: str) -> ExtractionResult:
    import zipfile
    import xml.etree.ElementTree as ET

    result = ExtractionResult()
    try:
        with zipfile.ZipFile(filepath) as zf:
            try:
                with zf.open("word/document.xml") as f:
                    tree = ET.parse(f)
            except (KeyError, ET.ParseError) as e:
                return ExtractionResult(error=f"Couldn't open this Word document ({e}).")

            body = tree.getroot().find(f"{_W_NS}body")
            if body is None:
                return ExtractionResult(error="This document has no readable body text.")

            heading_ids = _docx_heading_style_ids(zf)

            parts = []
            offset = 0
            for para in body.findall(f"{_W_NS}p"):
                text = "".join(node.text or "" for node in para.iter(f"{_W_NS}t")).strip()
                if not text:
                    continue
                p_pr = para.find(f"{_W_NS}pPr")
                p_style = p_pr.find(f"{_W_NS}pStyle") if p_pr is not None else None
                style_id = p_style.get(f"{_W_NS}val", "") if p_style is not None else ""
                if style_id in heading_ids:
                    result.headings.append((text, offset))
                parts.append(text)
                offset += len(text) + 1

            result.text = "\n".join(parts)

            # Best-effort: pull out embedded pictures too, same idea as the
            # PDF path -- every image in a .docx lives loose under
            # word/media/, so no relationship-file parsing is even needed.
            try:
                media_names = sorted(n for n in zf.namelist() if n.startswith("word/media/"))
                for name in media_names:
                    if len(result.images) >= MAX_IMAGES_PER_FILE:
                        break
                    ext = os.path.splitext(name)[1].lower().lstrip(".")
                    mime_type = IMAGE_EXTS.get(ext)
                    if not mime_type:
                        continue
                    result.images.append(_to_data_url(zf.read(name), mime_type))
            except Exception:
                pass
    except (zipfile.BadZipFile, OSError) as e:
        return ExtractionResult(error=f"Couldn't open this Word document ({e}).")

    if not result.text.strip() and not result.images:
        result.error = "This document has no readable text or pictures."
    return result


def _extract_doc(filepath: str) -> ExtractionResult:
    """Legacy binary .doc -- no reliable pure-Python offline reader.

    We try the .docx reader in case the file is mislabeled, otherwise fail
    loudly with a clear, actionable message rather than silently.
    """
    try:
        result = _extract_docx(filepath)
        if not result.error:
            return result
    except Exception:
        pass
    return ExtractionResult(
        error="Legacy .doc files aren't fully supported offline. "
              "Please re-save the file as .docx or .pdf and re-upload."
    )


def _extract_txt(filepath: str) -> ExtractionResult:
    encodings = ("utf-8", "utf-16", "latin-1")
    for enc in encodings:
        try:
            with open(filepath, "r", encoding=enc) as f:
                text = f.read()
            if not text.strip():
                return ExtractionResult(error="This text file appears to be empty.")
            return ExtractionResult(text=text)
        except (UnicodeDecodeError, UnicodeError):
            continue
        except Exception as e:
            return ExtractionResult(error=f"Couldn't read this text file ({e}).")
    return ExtractionResult(error="Couldn't decode this text file's encoding.")


EXTRACTORS = {
    "pdf": _extract_pdf,
    "docx": _extract_docx,
    "doc": _extract_doc,
    "txt": _extract_txt,
    "image": _extract_image,
}

# A line that starts a new enumerated item -- "A.", "b)", "139.", "1)", or
# a Roman-numeral sub-item ("I.", "II.", "III.", "IV." -- common in PH
# board-exam reviewers). Capped at X (1-10); enough for reviewer sub-items
# without risking a match on an ordinary capitalized word.
_ENUM_START_RE = re.compile(r"^(?:[A-Za-z]|\d{1,4}|I{1,3}|IV|VI{0,3}|IX|X)[.\)]\s+")
_SENTENCE_END_RE = re.compile(r'[.!?:;]["\')\]]?$')


def _reflow_paragraph(paragraph: str) -> str:
    """PDFs (and some DOCX exports) hard-wrap text at the visual line width,
    leaving a literal newline in the middle of a sentence. Left as-is, that
    breaks anything downstream that treats a line as a complete sentence
    (truncated 'definitions', answer options cut off mid-phrase). This joins
    wrapped lines back into flowing sentences, while keeping each enumerated
    item (numbered questions, lettered answer choices) on its own line."""
    out_lines: list[str] = []
    buf = ""
    for raw_line in paragraph.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        starts_new_item = bool(_ENUM_START_RE.match(line))
        if buf and not starts_new_item and not _SENTENCE_END_RE.search(buf):
            buf = f"{buf} {line}"
        else:
            if buf:
                out_lines.append(buf)
            buf = line
    if buf:
        out_lines.append(buf)
    return "\n".join(out_lines)


def clean_text(text: str) -> str:
    """Strip page numbers, stray whitespace, collapse blank lines, and
    reflow hard-wrapped lines back into whole sentences."""
    lines = text.splitlines()
    cleaned = []
    for line in lines:
        stripped = line.strip()
        if re.fullmatch(r"(page\s*)?\d{1,4}(\s*/\s*\d{1,4})?", stripped, flags=re.IGNORECASE):
            continue  # standalone page-number line
        cleaned.append(stripped)
    text = "\n".join(cleaned)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = "\n\n".join(_reflow_paragraph(p) for p in re.split(r"\n\s*\n", text))
    return text.strip()


def extract_text(filepath: str) -> ExtractionResult:
    """Main entry point: Steps 1-3 of the parsing pipeline."""
    if not os.path.exists(filepath):
        return ExtractionResult(error="File not found.")

    file_type = detect_file_type(filepath)
    extractor = EXTRACTORS.get(file_type)
    if extractor is None:
        return ExtractionResult(
            error=f"Unsupported file type '{file_type or 'unknown'}'. "
                  f"Supported formats: PDF, DOCX, DOC, TXT, and pictures "
                  f"(PNG/JPG/JPEG/WEBP/GIF/BMP)."
        )

    result = extractor(filepath)
    if result.error:
        return result

    result.text = clean_text(result.text)
    # A file with too little text is only a problem if it also has no
    # pictures to fall back on -- a picture-only upload (or a scanned page
    # captured as an image) is valid as long as a vision model can read it.
    if len(result.text) < 20 and not result.images:
        result.error = "This file doesn't contain enough text (or pictures) to build a quiz from."
        return result

    return result
